apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gp-documents-api
  description: |
    Backend service that implements GP Documents API, allows clinical documents
    to be exchanged between healthcare systems.
  labels:
    system: gp
    example.com/service-discovery-name: gp-docs-api
  annotations: {}
spec:
  type: service
  lifecycle: production
  owner: platform-team
